### ISSUE TITLE
更新不了

### ISSUE THREAD

**Issue by eugle** [jianboy/github-host#1]
更新到最新的host，但是仍然更新不了，如下图
![image](https://user-images.githubusercontent.com/24447931/120101180-50744c00-c177-11eb-815f-e9e69ad9862e.png)

会显示这样的错误
![image](https://user-images.githubusercontent.com/24447931/120101486-e65ca680-c178-11eb-8678-bddf8900ab9f.png)

**Comment by jianboy** [comment]
请增加描述信息，不清楚您的问题是什么
